# ==================================================
#               전역 설정 (Global Settings)
# ==================================================
# experiment_name: "unified_experiment_run" # 자동 생성되므로 주석 처리 또는 삭제
experiment_type: 'ox'   # 실행할 실험 유형 선택: 'choice', 'ox', 'open'
model_name: 'gemini-2.0-flash-lite'
output_dir: 'results/'

# ==================================================
#            실험 유형별 상세 설정 (Experiments)
# ==================================================
experiments:
  # --- 1. 객관식(choice) 실험 설정 ---
  choice:
    prompt_type: 'zero-shot'
    num_iterations: 30
    num_samples: 100           # 반복당 샘플링할 '총' 문제 수 (검증용)
    input_file: 'data/questionbank.xlsx'
    samples_per_category:
      '문장형_4지1답': 51
      '문장형_4지2답': 11
      '안전표지형_4지1답': 10
      '사진형_5지2답': 12
      '일러스트형_5지2답': 14
      '동영상형_4지1답': 2
    prompt_columns:
      question: 'question'
      options: 'options'

  # --- 2. OX 실험 설정 ---
  ox:
    base_result_file: 'results/choice_zero-shot_gemini-2.0-flash-lite_30x100.csv' # 참조할 choice 결과 파일
    target_category: '문장형_4지1답'
    prompt_columns:
      question: 'ox_question'

  # --- 3. 오픈형(open) 실험 설정 ---
  open:
    prompt_type: 'zero-shot'
    num_iterations: 10
    num_samples: 50
    input_file: 'data/questionbank.xlsx'
    prompt_columns:
      question: 'open_question'